### ISSUE TITLE
Unresponsive UI/RPC

### ISSUE THREAD

**Issue by john-connor** [whphhg/vcash-webui#5]
Using the latest version tested in FireFox and Chrome both end up spinning (javascript) and I start getting console errors (even though 9195 is responding):

{ [Error: connect ETIMEDOUT 127.0.0.1:9195]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9195 }

Previous versions no longer work (they crash).

**Comment by whphhg** [comment]
Tested on installs below with a fresh git pull & npm install and it ran without issues.
- Arch (Firefox 47.0, Chromium 51.0.2704.106)
- Ubuntu (Firefox 47.0)
- Windows 7 (Firefox 47.0.1)

**Comment by whphhg** [comment]
Tried fresh installs on Arch, Ubuntu and Windows 7 and they ran without issues, except on Ubuntu it ran into a problem with geoip response and crashed. Since the api I've used initially is back online, I've reverted back to it (pushed to github) and will keep the webui running on above installs while I sleep to see if any other errors pop up.

**Comment by john-connor** [comment]
Safari on Mac OS X and Mozilla both become unresponsive (javascript). I'll have to try on another machine.

**Comment by john-connor** [comment]
On RPi we tried kweb(it locked up) and chromium and epiphany both crash the underlying code: routes/index.js:1159 Promise is not defined.

**Comment by whphhg** [comment]
You're using a version of Node.js that doesn't have built-in promise support, same issue as #3. Solution is to update to the latest version.
